# --- PUERTO DE SALIDA PARA EUREKA ---
server.port=8761
spring.application.name=eureka-server

# --- CONFIGURACIÓN DE SERVIDOR (SOLO INFRAESTRUCTURA) ---
# Evita que el servidor Eureka se registre a sí mismo como cliente
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# --- NOMBRE DEL HOST ---
eureka.instance.hostname=localhost